steps:
    - name: 'gcr.io/cloud-builders/npm'
      args: ['install']
      dir: '.'
    - name: 'gcr.io/cloud-builders/npm'
      args: ['run', 'lint']
      dir: '.'
    - name: 'gcr.io/cloud-builders/npm'
      args: ['run', 'build']
      dir: '.'
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
          [
              'functions',
              'deploy',
              'bot-${_FUNCTION_NAME}',
              '--trigger-http',
              '--runtime',
              'nodejs12',
              '--region',
              'europe-west3',
              '--entry-point',
              'bot',
              '--memory',
              '128MB',
              '--set-env-vars',
              'BOT_TOKEN=${_BOT_TOKEN}'
          ]
      dir: '.'
